### ISSUE TITLE
Ascent script issue 2 seconds into roll

### ISSUE THREAD

**Issue by ChrisGNSF** [giuliodondi/kOS-Shuttle_OPS1#3]
Discovered a bug in the launch script.  About 2 seconds into the roll program, the script seems to be breaking.  Attaching screenshot of the error messages in kOS.

![Screenshot (1)](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/121457826/575c5d82-b0bc-4c93-8101-b89cf79cd6c4)

**Comment by giuliodondi** [comment]
The error stack trace is truncated by the terminal, I don't have full visibility of what / where the issue is exactly.
In any case, I just tried the master branch code and saw no such issue, maybe try to pull the latest

**Comment by ChrisGNSF** [comment]
Ah. I expanded the window. This is with a fresh install of the ascent script.

![Screenshot (2)](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/121457826/65421593-84f2-46bf-8cb0-5b7a7f57cd51)

**Comment by giuliodondi** [comment]
This is not a bug with the script: the script attemtps to log telemetry to a csv file, but kOS seems to be configured with limited cpu storage and it fails when the log file gets too big (hence why it happens around 8 seconds, which seems an oddly random time).
I never got this error because I didn't configure kOS to behave "realistically" in this way, it could be because I always play sandbox exclusively.

A straightforward workaround is to go to the launcher script 'shuttle.ks' and set log_telemetry to 'FALSE', but I don't guarantee that nothing else will break in these conditions.

**Comment by ChrisGNSF** [comment]
That worked!  Thank you.
